### ISSUE TITLE
Вёрстка главной страницы

### ISSUE THREAD

**Issue by NitrocinEagle** [ArtyomAnisimov/livelibkiller#17]
Вот [тут](https://pp.vk.me/c836533/v836533093/12733/njEbaJK7hew.jpg) накидали макет.
Вот шаблон для [главной страницы](https://github.com/ArtyomAnisimov/livelibkiller/blob/master/templates/home/index.html)

Там есть верхняя, нижняя и боковая части. Они вынесены в блоки navbar, footer и sidebar в [базовом ](https://github.com/ArtyomAnisimov/livelibkiller/blob/master/templates/base/base.html)шаблоне

**Comment by NitrocinEagle** [comment]
Пока верстаешь, можешь кидать фейковые данные. Попутно можешь сюда писать, какие данные нужны из БД. Например, список книг, данные по книгам(лайки для каждой книги и т.д.)

**Comment by romanyakovlev** [comment]
Посмотри, что получилось.
