### ISSUE TITLE
Создать главную страницу

### ISSUE THREAD

**Issue by NitrocinEagle** [ArtyomAnisimov/livelibkiller#2]
Блоки header и footer вынесены в отдельные файлы. 
Главная страница находится в 'home/index'. Унаследоана от базового шаблона. Илья, нужно существующую твою страницу переразбить на блоки.

**Comment by krylovilya** [comment]
- [x] **done.**

**Comment by NitrocinEagle** [comment]
Убери fixed в navbar'е, чтоб выезжать и заезжать могла панель

**Comment by krylovilya** [comment]
Но зачем? Пусть будет как здесь materializecss.com

**Comment by NitrocinEagle** [comment]
Затем, что ей не надо постоянно на виду находиться и сливаться с основным контентом

**Comment by krylovilya** [comment]
Готово
