### ISSUE TITLE
Модель "Книга пользователя"

### ISSUE THREAD

**Issue by NitrocinEagle** [ArtyomAnisimov/livelibkiller#4]
Описать модель `UsersBook`. Она [тут](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/apps/user/models.py)

[Фоты](https://goo.gl/photos/ceJKMWBwYMTAWVfP9)

**Comment by holyslippers** [comment]
Готово. Гляди)

**Comment by NitrocinEagle** [comment]
Исправляй
