### ISSUE TITLE
Сделать главную страницу доступной по ссылке '/'

### ISSUE THREAD

**Issue by NitrocinEagle** [ArtyomAnisimov/livelibkiller#6]
Сделать главную страницу доступной по ссылке '/'. 
[Шаблон для главной страницы ](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/templates/home/index.html)
[urls ](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/apps/home/urls.py)и [views ](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/apps/home/views.py)в приложении [home](https://github.com/ArtyomAnisimov/-livelibkiller/tree/master/apps/home)
Не забудь через include подключить urls приложения home в корневом [urls](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/apps/urls.py)

**Comment by krylovilya** [comment]
- [ ] **done.**

**Comment by NitrocinEagle** [comment]
[комменты](https://github.com/ArtyomAnisimov/-livelibkiller/commit/7ca0dd404b28001b78b24f2f21451c275ce2556c)

**Comment by krylovilya** [comment]
- [ ] **done.**

**Comment by krylovilya** [comment]
- [x] **done.** ?
