### ISSUE TITLE
Шаблон для страницы '/login'

### ISSUE THREAD

**Issue by NitrocinEagle** [ArtyomAnisimov/livelibkiller#7]
Вот [тут](https://github.com/ArtyomAnisimov/-livelibkiller/tree/master/templates/home) новый шаблон создать надо. 
Унаследоваться от 'base/base.html',  сделать пустыми блоки  

```
{% block header %}
{% endblock %}
{% block footer %}
{% endblock %}
```

В этом блоке формочка для входа

`{% block content %}

<some_form></some_form>

{% endblock %}`

шаблон назвать login.html

[Forms-material](http://materializecss.com/forms.html)

**Comment by pc-mist** [comment]
шаблон назвать login.html

**Comment by qqeekk** [comment]
login.css сюда заливать?
https://github.com/ArtyomAnisimov/-livelibkiller/tree/master/static/css/home

**Comment by NitrocinEagle** [comment]
да
