### ISSUE TITLE
Шаблон для страницы регистрации

### ISSUE THREAD

**Issue by NitrocinEagle** [ArtyomAnisimov/livelibkiller#8]
Вот [тут](https://github.com/ArtyomAnisimov/-livelibkiller/tree/master/templates/home) новый шаблон создать надо. 
Унаследоваться от 'base/base.html',  сделать пустыми блоки  

```
{% block header %}
{% endblock %}
{% block footer %}
{% endblock %}
```

В этом блоке формочка для регистрации

`{% block content %}

<some_registration_form></some_registration_form>

{% endblock %}`

**Comment by pc-mist** [comment]
Это Можайскому задача

**Comment by krylovilya** [comment]
Готово

**Comment by NitrocinEagle** [comment]
в home перенеси reg.html

**Comment by krylovilya** [comment]
Готово
