### ISSUE TITLE
Сделать страницу для входа доступной по ссылке '/login'. 

### ISSUE THREAD

**Issue by NitrocinEagle** [ArtyomAnisimov/livelibkiller#9]
[Шаблон для страницы входа](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/templates/home/login.html)
[urls ](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/apps/home/urls.py)и [views ](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/apps/home/views.py)в приложении [home](https://github.com/ArtyomAnisimov/-livelibkiller/tree/master/apps/home)
Убедись, что через include подключены urls приложения home в корневом [urls](https://github.com/ArtyomAnisimov/-livelibkiller/blob/master/apps/urls.py). Если не подключены - подключи и измени запись об этом в задаче #6 

Более того. По get-запросу на '/login' возвращается страница входа. А по post-запросу отсылаются данные формы. 
Тут либо пригодится `django.views.generic.FormView`, либо готовая `LoginView`, которая где-то должна валяться в Django

**Comment by ArtyomAnisimov** [comment]
Попробовал сделать, создал ветку, точнее вроде как две(случайно-специально), но не знаю правильно ли стырил метод для get/post запроса.
